galaxy_info:
  role_name: common
  author: 'Dialy burleigh'
  description: 'install prerequis using ansible'
  license: MIT
  min_ansible_version: 2.7
  platforms:
   - name: Debian
     versions:
      - stretch
      - buster
   - name: Ubuntu
     versions:
      - xenial
      - bionic
   - name: EL 
     versions:
      - 7
      - 8
  galaxy_tags: 
   - system
   - devops
   - docker
   - kubernetes
   
dependencies: 