all:
  hosts:
    master:
      ansible_host: 172.28.128.3
      vars:
        ansible_hostname: centos8
    workers-1:
      ansible_host: 172.28.128.4
      vars:
        ansible_hostname: centos7
    workers-2:
      ansible_host: 172.28.128.19
      vars:
        ansible_hostname: buster
  children:
    workers:
     hosts:
      workers-1:
      workers-2:
    

