- name: Copy the docker repository definition [RHEL]
  copy: 
    src: docker-ce.repo 
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '660'
  when: ansible_facts['os_family']  == 'RedHat'


- name: Copy the EPEL7 repository definition [RHEL]
  copy: 
    src: epel.repo 
    dest: /etc/yum.repos.d/epel.repo 
    mode: '660'
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: Copy the EPEL8 repository definition [RHEL]
  copy: 
    src: epel8.repo 
    dest: /etc/yum.repos.d/epel.repo
    mode: '660'
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- name: Copy the kubernetes repository definition [RHEL]
  copy: 
    src: kubernetes.repo 
    dest: /etc/yum.repos.d/kubernetes.repo 
    mode: '660'
  when: ansible_facts['os_family']  == 'RedHat' 

- name: Create the GPG key for docker [RHEL]
  copy: 
    src: gpg 
    dest: /etc/pki/rpm-gpg
    mode: '660'
  when: ansible_facts['os_family']  == 'RedHat' 

- name: Create the GPG key for EPEL7 [RHEL]
  copy: 
    src:  RPM-GPG-KEY-EPEL-7 
    dest: /etc/pki/rpm-gpg
    mode: '660'
  when: ansible_facts['os_family']  == 'RedHat' and ansible_facts['distribution_major_version']== "7"

- name: Create the GPG key for EPEL8 [RHEL]
  copy: 
    src: RPM-GPG-KEY-EPEL-8 
    dest: /etc/pki/rpm-gpg
    mode: '660'
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8"

- name: Create the GPG key for kubernetes [RHEL]
  copy: 
    src: rpm-package-key.gpg 
    dest: /etc/pki/rpm-gpg/rpm-package-key.gpg 
    mode: '660'
  when: ansible_facts['os_family']  == 'RedHat' 

- name: Create the GPG key for kubernetes suite [RHEL]
  copy: 
    src: yum-key.gpg 
    dest: /etc/pki/rpm-gpg/yum-key.gpg 
    mode: '660'
  when: ansible_facts['os_family']  == 'RedHat' 

- name: Copy the EPEL8 BASE AppStream repository definition [RHEL]
  copy: 
    src: rhel8.repo
    dest: /etc/yum.repos.d/rhel8.repo
    mode: '660'
  when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'