apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: kube-system
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
  selector:
    run: my-nginx
  